name: CI

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  JVM_OPTS: -Xmx3200m

jobs:
  check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Static analysis
        run: ./gradlew app:staticAnalysis app:collectSarifReports --continue --no-daemon

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() }}
        with:
          sarif_file: app/build/reports/sarif/
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Tests
        run: ./gradlew koverXmlReport --continue --no-daemon

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./app/build/reports/kover/project-xml/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results
